# -*- coding: utf-8 -*-
"""Yolo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XVUx9RibVxZtXKFZRWivfHAM8Dn0537P
"""

!pip install ultralytics

!yolo detect train model=yolov8n.pt data="/content/drive/MyDrive/deteksi/data.yaml" epochs=10

!yolo detect predict model="/content/runs/detect/train/weights/best.pt" source="/content/drive/MyDrive/deteksi/test/images"